version: '3.8'
services:
  app:
    image: pscirclecorerepo.azurecr.io/ps-circle-core-app:latest
    ports:
      - "8080:8080"
    environment:
      - ENV_NAME=any_value
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/ps-circle-db
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

volumes:
  mongo_data:
